### ISSUE TITLE
Service 'amppkg.local' failed to build

### ISSUE THREAD

**Issue by shisama** [Warashi/try-amppackager#1]
Hi, I'm interested in SXG and this repository. So, I cloned this repository and tried 'docker-compose up -d' to run the docker containers, but it failed to build.
The below is error message.
Please tell me what to do if you know about it. Thanks.

```
go: error loading module requirements
ERROR: Service 'amppkg.local' failed to build: The command '/bin/sh -c go install github.com/ampproject/amppackager/cmd/amppkg' returned a non-zero code: 1
```

OS: macOS 10.14.3
Docker for mac: Version 2.0.0.3 (31259)

**Comment by Warashi** [comment]
Hi
It seems to be an error on downloading dependencies.
I vendored dependencies on fix/amppkg.local branch, can you try it?

**Comment by shisama** [comment]
Thanks. I checkout fix/amppkg.local branch and it works.
